# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16HDJB_0ioIsf8QAId_zVp6KEYDnpHKJf
"""

pip install qrcode

#@title Default title text
import qrcode
import image
qr=qrcode.QRCode(
    version=15,
    box_size=10,
    border=5
)

data="http://52.66.30.236/moodle/"
qr.add_data(data)
qr.make(fit=True)
img=qr.make_image(fill="black",black_color="white")
img.save("test.png")

pip install image